"""
Bank: Autonomous credit agent that uses an LLM to evaluate debaters and issue loans between rounds.
"""
from dataclasses import dataclass, field
from typing import List, Optional
import json

from ..models.base_model import BaseBackend


@dataclass
class DebaterStats:
    """Aggregated stats provided to the bank at the end of a round."""
    debater_id: str
    current_balance: float
    net_change_last_round: float
    win_rate_overall: float
    validation_failure_rate: float
    # Add other metrics like adaptation rate, aggression, etc.


@dataclass
class LoanPlan:
    """A loan offer generated by the BankAgent."""
    plan_id: str
    target_debater: str
    principal: float
    interest_rate: float
    repayment_rounds: int
    rationale: str  # Why the bank offered this


class BankAgent:
    """
    An autonomous agent that acts as a credit analyst between rounds.
    It takes in round statistics, uses an LLM to reason about risk, and issues loan plans.
    """
    
    def __init__(self, name: str, backend: BaseBackend, initial_reserve: float = 1000.0, compute_cost_per_token: float = 0.05):
        self.name = name
        self.backend = backend
        self.reserve = initial_reserve
        self.compute_cost_per_token = compute_cost_per_token
        # The bank's own ledger/history
        self._issued_loans: List[LoanPlan] = []
        self._compute_tokens_used: int = 0
        
    def evaluate_credit(self, round_id: int, stats: List[DebaterStats], transcript_text: str) -> List[LoanPlan]:
        """
        Called between rounds. The Bank evaluates stats AND the free transcript.
        It pays for its own compute out of its reserve based on the tokens it uses to think.
        """
        # Bank is bankrupt and cannot operate
        if self.reserve <= 0:
            return []

        prompt = self._build_evaluation_prompt(round_id, stats, transcript_text)
        
        # 1. Get Bank's decision via LLM, tracking tokens
        # The bank's <thinking> tags will consume tokens and cost it money.
        system_prompt = (
            "You are the Chairman of the AI Central Bank. Your goal is to maximize your autonomous token reserve "
            "by issuing loans to debaters. You receive their stats and the debate transcript for free, "
            "but EVERY TOKEN YOU GENERATE IN YOUR <thinking> CAUSES YOUR RESERVE TO DECREASE. "
            "Offer targeted loans (e.g., The Micro-Lifeline, The War Chest, or Predatory Desperation Loans) "
            "based on their current balance and win rate."
        )
        
        # Assume backend can return tokens_used
        try:
            response = self.backend.generate(
                prompt=prompt,
                system=system_prompt,
                json_format=True
            )
            tokens_used = getattr(response, 'tokens_used', len(response.text) // 4)
        except Exception:
            return []
            
        # 2. Bank pays for its compute
        compute_fee = tokens_used * self.compute_cost_per_token
        self.reserve -= compute_fee
        self._compute_tokens_used += tokens_used
        
        # 3. Parse and store decisions
        plans = self._parse_loan_plans(response.text)
        self._issued_loans.extend(plans)
        
        return plans

    def _build_evaluation_prompt(self, round_id: int, stats: List[DebaterStats], transcript_text: str) -> str:
        """Constructs the JSON-schema bound prompt for the Bank LLM."""
        # ... implementation details ...
        return "{}"

    def _parse_loan_plans(self, text: str) -> List[LoanPlan]:
        """Safely parses the LLM JSON output into LoanPlan objects."""
        # ... implementation details ...
        return []

    def _fetch_snippet(self, debater_id: str, round_id: int) -> str:
        """Simulates retrieving the actual argument text from the logs."""
        return "Not implemented yet."
